# Custom tests example
# got-swag examples/petstore.yaml examples/vars.yaml
# The tests could be published by the service itself

swagger: "2.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
host: petstore.swagger.io
basePath: /v2
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /pet/findByStatus:
    get:
      summary: Finds pets by status
      parameters:
        - name: status
          in: query
          description: Status values that need to be considered for filter
          required: false
          type: array
          items:
            type: string
      responses:
        200:
          description: An array of pets
          schema:
            $ref: '#/definitions/Pets'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
      x-tests:
        - description: Should find pets
          steps:
            - get( '/v2/pet/findByStatus?status=available' )
            - log( res.json[ 0 ] )
            - log( res.json[ 1 ] )
            - equal( res.statusCode, 200 )
            - ok( res.json.length > 0 )
            - equal( typeof res.json[ 0 ].name, 'string' )
            - validate()
        - description: Should not find evil pets
          steps:
            - get( '/v2/pet/findByStatus?status=evil' )
            - deepEqual( res.json, [] )
            - validate()
definitions:
  Pet:
    required:
      - name
    properties:
      id:
        type: integer
      category:
        $ref: '#/definitions/Category'
      name:
        type: string
      tag:
        type: string
  Pets:
    type: array
    items:
      $ref: '#/definitions/Pet'

  Category:
    properties:
      id:
        type: integer
      name:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
